language: php

sudo: false

php:
  - 5.5
  - 5.6
  - hhvm

env:
  - FIREBASE_JWT_VERSION=2.0.0 GUZZLE_VERSION=5.3
  - FIREBASE_JWT_VERSION=2.0.0 GUZZLE_VERSION=~6.0
  - FIREBASE_JWT_VERSION=3.0.0 GUZZLE_VERSION=5.3
  - FIREBASE_JWT_VERSION=3.0.0 GUZZLE_VERSION=~6.0

before_script:
  - composer install
  - composer require firebase/php-jwt:$FIREBASE_JWT_VERSION
  - composer require guzzlehttp/guzzle:$GUZZLE_VERSION

script:
  - vendor/bin/phpunit
  - vendor/bin/phplint src/
  - vendor/bin/phplint tests/
