name: Generate Documentation
on:
    push:
        branches:
            - master
        tags:
            - "*"

jobs:
    docs:
        name: "Generate Project Documentation"
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
        - name: API Documentation Generation
          uses: varunsridharan/action-apigen@master
          with:
            source_folder: src
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
